<?php

return [
    [
        'name' => 'access_key_id',
        'title' => 'AWS Access Key ID',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => 'AWS 访问密钥 ID（可在 AWS IAM 控制台获取）',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'secret_access_key',
        'title' => 'AWS Secret Access Key',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => 'AWS 访问密钥（可在 AWS IAM 控制台获取）',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'bucket',
        'title' => 'S3 Bucket名称',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => 'AWS S3 的存储桶名称，例如：my-bucket',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'region',
        'title' => 'S3 Region',
        'type' => 'string',
        'content' => [],
        'value' => 'us-east-1',
        'rule' => 'required',
        'msg' => '',
        'tip' => 'AWS S3 区域，例如：us-east-1, us-west-2, ap-southeast-1',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'cdnurl',
        'title' => 'CDN地址',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => 'required;cdnurl',
        'msg' => '',
        'tip' => '请填写 CDN 地址或 S3 访问地址，例如：https://my-bucket.s3.us-east-1.amazonaws.com，必须以 http(s):// 开头',
        'ok' => '',
        'extend' => 'data-rule-cdnurl="[/^http(s)?:\\/\\/.*$/, \'必需以http(s)://开头\']"',
    ],
    [
        'name' => 'uploadmode',
        'title' => '上传模式',
        'type' => 'select',
        'content' => [
            'server' => '服务器中转(推荐)',
        ],
        'value' => 'server',
        'rule' => '',
        'msg' => '',
        'tip' => '服务器中转模式：文件先上传到服务器，再由服务器上传到 S3',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'serverbackup',
        'title' => '服务器备份',
        'type' => 'radio',
        'content' => [
            1 => '备份(附件管理将产生2条记录)',
            0 => '不备份(推荐)',
        ],
        'value' => '0',
        'rule' => '',
        'msg' => '',
        'tip' => '服务器中转模式下是否备份文件到本地（不备份可节省服务器存储空间）',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'savekey',
        'title' => '保存文件名',
        'type' => 'string',
        'content' => [],
        'value' => '/uploads/{year}{mon}{day}/{filemd5}{.suffix}',
        'rule' => 'required',
        'msg' => '',
        'tip' => '文件保存路径模板，支持变量：{year}、{mon}、{day}、{filemd5}、{.suffix}',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'expire',
        'title' => '上传有效时长',
        'type' => 'string',
        'content' => [],
        'value' => '600',
        'rule' => 'required',
        'msg' => '',
        'tip' => '用户停留页面上传有效时长，单位：秒',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'maxsize',
        'title' => '最大可上传',
        'type' => 'string',
        'content' => [],
        'value' => '100M',
        'rule' => 'required',
        'msg' => '',
        'tip' => '单个文件最大上传大小，例如：10M、100M、1G',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mimetype',
        'title' => '可上传后缀格式',
        'type' => 'string',
        'content' => [],
        'value' => 'jpg,png,bmp,jpeg,gif,webp,zip,rar,xls,xlsx,pdf,doc,docx',
        'rule' => 'required',
        'msg' => '',
        'tip' => '允许上传的文件扩展名，用英文逗号分隔',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'multiple',
        'title' => '多文件上传',
        'type' => 'bool',
        'content' => [],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '是否允许同时上传多个文件',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'chunking',
        'title' => '分片上传',
        'type' => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '大文件分片上传（推荐大文件开启）',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'chunksize',
        'title' => '分片大小',
        'type' => 'number',
        'content' => [],
        'value' => '4194304',
        'rule' => 'required',
        'msg' => '',
        'tip' => '分片大小（字节），默认 4MB (4194304 字节)',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'syncdelete',
        'title' => '同步删除S3文件',
        'type' => 'bool',
        'content' => [],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '附件删除时是否同步删除 S3 上的文件',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'apiupload',
        'title' => 'API接口使用S3存储',
        'type' => 'bool',
        'content' => [],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => 'API 接口（/api/common/upload）是否使用 S3 存储',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'disable_acl',
        'title' => '禁用ACL',
        'type' => 'bool',
        'content' => [],
        'value' => '0',
        'rule' => '',
        'msg' => '',
        'tip' => '某些 S3 兼容服务不支持 ACL，可选择禁用（AWS S3 请保持关闭）',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'skip_ssl_verify',
        'title' => '跳过SSL验证',
        'type' => 'bool',
        'content' => [],
        'value' => '0',
        'rule' => '',
        'msg' => '',
        'tip' => '仅用于开发环境，生产环境请保持关闭',
        'ok' => '',
        'extend' => '',
    ],
];
